# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CadastroClienteController.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.domain.Cliente import Cliente
from model.dao.ClienteDAO import ClienteDAO

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 468)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(120, 400, 141, 28))
        self.pushButton.setObjectName("pushButton")
        self.nome = QtWidgets.QLineEdit(Dialog)
        self.nome.setGeometry(QtCore.QRect(30, 40, 341, 31))
        self.nome.setObjectName("nome")
        self.sobrenome = QtWidgets.QLineEdit(Dialog)
        self.sobrenome.setGeometry(QtCore.QRect(30, 90, 341, 31))
        self.sobrenome.setObjectName("sobrenome")
        self.dataNascimento = QtWidgets.QDateEdit(Dialog)
        self.dataNascimento.setGeometry(QtCore.QRect(30, 140, 110, 22))
        self.dataNascimento.setObjectName("dataNascimento")
        self.telContato = QtWidgets.QLineEdit(Dialog)
        self.telContato.setGeometry(QtCore.QRect(30, 170, 341, 31))
        self.telContato.setObjectName("telContato")
        self.dataCadastro = QtWidgets.QDateEdit(Dialog)
        self.dataCadastro.setGeometry(QtCore.QRect(30, 210, 110, 22))
        self.dataCadastro.setObjectName("dataCadastro")
        self.cpf = QtWidgets.QLineEdit(Dialog)
        self.cpf.setGeometry(QtCore.QRect(30, 240, 341, 31))
        self.cpf.setObjectName("cpf")
        self.idEndereco = QtWidgets.QLineEdit(Dialog)
        self.idEndereco.setGeometry(QtCore.QRect(30, 290, 341, 31))
        self.idEndereco.setObjectName("idEndereco")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Inserir"))
        
        self.pushButton.clicked.connect(self.inserir_dados)
        
    def inserir_dados(self, ):

        cliente = Cliente()
        clienteDAO = ClienteDAO()
        
        cliente.nome = self.nome.text()
        cliente.sobrenome = self.sobrenome.text()
        cliente.datanascimento = self.dataNascimento.text()
        cliente.telcontato = self.telContato.text()
        cliente.datacadastro = self.dataCadastro.text()
        cliente.cpf = self.cpf.text()
        cliente.idendereco = self.idEndereco.text()
        
        clienteDAO.insert(cliente)


        
