# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/CadastroClienteView.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import QWidget
from PyQt5.uic import loadUi

from model.domain.Cliente import Cliente
from model.domain.Endereco import Endereco
import datetime

class TelaCliente(QWidget):
    def __init__(self):
        super().__init__()
        loadUi('src/view/CadastroClienteView.ui', self)
        self.btn_cadastrar_cliente.clicked.connect(self.inserir_dados)
    
    def inserir_dados(self):
        try:
            cliente = Cliente()
            endereco = Endereco()
            
            cliente.nome = self.input_nome.text()
            cliente.sobrenome = self.input_sobrenome.text()
            cliente.data_nascimento = self.input_date.text()
            cliente.tel_contato = self.input_telefone.text()
            cliente.cpf = self.input_cpf.text()
            cliente.data_cadastro = datetime.date.today()
            
            # Endereço do cliente
            endereco.rua = self.input_rua.text()
            endereco.numero = self.input_numero.text()
            endereco.bairro = self.input_bairro.text()
            endereco.cidade = self.input_cidade.text()
            endereco.uf = self.input_uf.text()
            cliente.endereco = endereco
            
            self.clienteDAO.insert(cliente)
            QMessageBox.information(self.layoutWidget, 'Alerta', 'Sucesso ao cadastrar o Cliente.')
        except Exception as e:
            QMessageBox.critical(self.layoutWidget, 'Alerta', f'Error ao cadastrar o Cliente.')