# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/TelaPrincipalView.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QMainWindow
from controller.CadastroProdutoController import Ui_Form as CadastroProduto
from controller.CadastroClienteController import Ui_Form as CadastroCliente
import resources_rc
from PyQt5.uic import loadUi

class Ui_MainWindow(object):

    def configure_stackWidgets(self):
        self.page_produtos = TelaProdutos()
        self.page_clientes = TelaClientes()

        self.stackedWidget.addWidget(self.page_produtos)
        self.stackedWidget.addWidget(self.page_clientes)

        self.btn_inicio_min.clicked.connect(self.btn_inicio_clicked)
        self.btn_inicio_max.clicked.connect(self.btn_inicio_clicked)
        self.btn_vendas_min.clicked.connect(self.btn_vendas_clicked)
        self.btn_vendas_max.clicked.connect(self.btn_vendas_clicked)
        self.btn_produtos_min.clicked.connect(self.btn_produtos_clicked)
        self.btn_produtos_max.clicked.connect(self.btn_produtos_clicked)

        self.btn_clientes_min.clicked.connect(self.btn_clintes_clicked)
        self.btn_clientes_max.clicked.connect(self.btn_clintes_clicked)

        self.btn_side_menu_collapse.toggle()

    def btn_inicio_clicked(self):
        self.stackedWidget.setCurrentIndex(0)

    def btn_vendas_clicked(self):
        self.stackedWidget.setCurrentIndex(1)

    def btn_produtos_clicked(self):
        self.stackedWidget.setCurrentIndex(4)
    
    def btn_clintes_clicked(self):
        self.stackedWidget.setCurrentIndex(5)

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

class TelaProdutos(QWidget):
    def __init__(self):
        super().__init__()
        self.ui = CadastroProduto()
        self.ui.setupUi(self)

class TelaClientes(QWidget):
    def init(self):
        super().init()
        self.ui = CadastroCliente()
        self.ui.setupUi(self)
        
class openTelaPrincipal(QMainWindow):
    def __init__(self):
        super().__init__()
        # Carregue a interface .ui
        loadUi('src/view/PrincipalView.ui', self)
        self.configureStackedWidget()
        self.openTelaClientes()
    
    def configureStackedWidget(self):
        self.btn_tela_vendas.clicked.connect(self.loadVendas)
        self.btn_tela_produtos.clicked.connect(self.loadProdutos)
        self.btn_tela_clientes.clicked.connect(self.loadClientes)
    
    def openTelaProdutos(self):
        self.btn_tela_produtos.clicked.connect(self.loadClientes)
        
    def openTelaClientes(self):
        self.btn_tela_clientes.clicked.connect(self.loadClientes)
        
    def loadVendas(self):
        self.stackedWidget.setCurrentIndex(1)
        
    def loadProdutos(self):
        self.page_produtos = TelaProdutos()
        self.stackedWidget.addWidget(self.page_produtos)
        self.stackedWidget.setCurrentIndex(2)
        
    def loadClientes(self):
        self.page_clientes = TelaClientes()
        self.stackedWidget.addWidget(self.page_clientes)
        self.stackedWidget.setCurrentIndex(3)
        